### ISSUE TITLE
Recreate categories - agribalyse mapping

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/off-category-classification#19]
We need a file that maps categories to agrybalise.

This can be done by parsing https://raw.githubusercontent.com/openfoodfacts/openfoodfacts-server/main/taxonomies/categories.result.txt

The format is explained here : https://wiki.openfoodfacts.org/Global_taxonomies#Format (we may update if needed).

We search for categories which have an agribalyse_food_code property.

**Comment by streino** [comment]
From [`Thresholds.ipynb`](https://github.com/openfoodfacts/off-category-classification/blob/master/Thresholds.ipynb), looks like `agribalyse_categories.txt` should be a list of normalized categories. Below is an extract of what we're trying to match against the agribalyze categories:
```
en:frozen-foods
en:pastry-helpers
en:marinated-anchovy-fillets-with-vegetable-oil
fr:yaourts-multifruits
fr:betises-de-cambrai
...
```

@alexgarel Is there a simple way to normalize the categories listed in [`categories.result.txt`](https://raw.githubusercontent.com/openfoodfacts/openfoodfacts-server/main/taxonomies/categories.result.txt)?
Otherwise, I'm thinking of extracting them from the `categories_tags` field in [`openfoodfacts-products.jsonl.gz`](https://static.openfoodfacts.org/data/openfoodfacts-products.jsonl.gz). Most likely taking only `categories_tags[-1]`, which I understand will be the narrowest category.

**Comment by alexgarel** [comment]
> Otherwise, I could also extract the normalized categories directly from the categories_tags field in [openfoodfacts-products.jsonl.gz](https://static.openfoodfacts.org/data/openfoodfacts-products.jsonl.gz), filtering for products that have an agribalyse_food_code. 

I think this is a good idea.

For normalization, I'm not sure, @stephanegigandet should know.

**Comment by alexgarel** [comment]
@streino I think you did it right ?

**Comment by stephanegigandet** [comment]
Sorry I missed the notification. The easiest way to get the mapping is to use the JSON file: https://world.openfoodfacts.org/data/taxonomies/categories.json
You have one entry for each category, and for each of them you have their properties, including the agribalyse_food_code and agribalyse_proxy_food_code

**Comment by streino** [comment]
Sorry I forgot to update the ticket. Yes I did generate an `agribalyse_categories.txt` file with the following script:

```
cat categories.json | jq -c -r '. | to_entries | .[] | select(.value.agribalyse_food_code != null) | .key' > agribalyse_categories.txt
```

I'm not sure where this file should go though. Is there a way to update https://github.com/openfoodfacts/openfoodfacts-ai/releases/tag/dataset-category-2021-09-15? Or just do another release?

I could confirm that using this file gives the same results in [Thresholds.ipynb]( https://github.com/openfoodfacts/off-category-classification/blob/fix-thresholds-notebook/Thresholds.ipynb) compared to the original version in `master`. At least the first few results; I haven't fixed the rest of the notebook yet.

**Comment by alexgarel** [comment]
@streino I can update the realese. Do you have the file ?

**Comment by alexgarel** [comment]
Sorry, I regenerated the file :-) and update [the release](https://github.com/openfoodfacts/openfoodfacts-ai/releases/tag/dataset-category-2021-09-15) ! 

I will now update the download.sh
