### ISSUE TITLE
install training project

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/off-category-classification#3]
Git clone, then follow readme

**Comment by 8huit** [comment]
Hello,
I’ve installed the training set and had to correct 2 files in order to run it:
- file requirements.txt : correct with tensorflow-datasets
-  file train.py: delete import utils.update.dict.dot

but afterwards, the training session stop after the tests data, i don’t know if it’s related to the corrections I made.

**Comment by alexgarel** [comment]
I close, this was an introductory issue.
